config/routes.rb
Rails.application.routes.draw do
  get 'individual_comments/index'

  get 'individual_user/show'

  get 'individual_links/index'

  post 'login/create' => 'login#create', as: 'login'

  get 'login/new' => 'login#new'

  post 'login/new' => 'login#post'

  delete 'logout' => 'login#destroy', as: 'logout'

  resources :users

  resources :links do
    resources :comments
  end

  root 'login#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
  validates :link, presence: true
  validates :user_id, presence: true
  validates :link_id, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments
  validates :user_id, presence: true
  validates :title, presence: true
  validates :url, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, presence: true, uniqueness: true
  validates :password, confirmation: true, presence: true
  has_many :links
  has_many :comments

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(password)
    @password = BCrypt::Password.create(password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate!
   redirect_to(login_path) unless current_user
  end

  def current_user
   @current_user ||= User.where(id: session[:user_id]).first
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_link, only: [:edit, :destroy, :update, :create]
  before_action :set_comment, only: [:edit, :destroy, :update]
  before_action :authorize_user_by_comment, only: [:edit, :destroy, :update]
  def edit
  end

  def destroy
    @comment.destroy
    redirect_to link_comments_path(link_id: @comment.link_id)
  end

  def update
    @comment.update(comment_params)
    redirect_to link_comments_path(link_id: @comment.link_id)
  end

  def create
    @comment = current_user.comments.create!(comment_params)
    redirect_to link_path(@link.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :link_id, :user_id)
  end

  def set_link
    @link = Link.find(params[:link_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def authorize_user_by_comment
    redirect_to(root_path, notice: "You have to be logged in to do that!" ) unless @comment.user == current_user
  end
end

app/controllers/individual_comments_controller.rb
class IndividualCommentsController < ApplicationController
  def index
    @comments = Comment.where(user_id: current_user.id)
  end
end

app/controllers/individual_links_controller.rb
class IndividualLinksController < ApplicationController
  def index
    @links = Link.where(user_id: current_user.id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :destroy, :update]
  before_action :authorize_user_by_link, only: [:edit, :destroy, :update]
  def index
    @links = Link.order(created_at: :desc).page params[:page]
  end

  def new
    @link = Link.new
  end

  def show
    @comment = Comment.new(link_id: @link.id)
  end

  def edit
  end

  def destroy
    @link.destroy
    redirect_to individual_links_index_path
  end

  def update
    @link.update(link_params)
    redirect_to action: "show", id: @link.id
  end

  def create
    @link = current_user.links.create(link_params)
    redirect_to individual_links_index_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :description, :url, :user_id)
  end

  def set_link
    @link = Link.find(params[:id])
  end

  def authorize_user_by_link
    redirect_to(root_path, notice: "You have to be logged in to do that" ) unless @link.user == current_user
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(user_name: user_params[:user_name])
    if @user && @user.password == user_params[:password]
      session[:user_id] = @user.id
      redirect_to links_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil if current_user
    redirect_to login_new_path
  end

  private

  def user_params
    params.permit(:user_name, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to login_new_path
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to action: "show", id: @user.id
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/individual_comments_helper.rb
module IndividualCommentsHelper
end

app/helpers/individual_links_helper.rb
module IndividualLinksHelper
end

app/helpers/individual_user_helper.rb
module IndividualUserHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<h4>Leave a Comment</h4>

  <%= form_for @comment, url: link_comments_path(@link.id) do |f| %>
  <%= f.hidden_field :link_id, value: @link.id %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>  
    <div class="form-group">
      <button type="submit" class="btn btn-success">Comment</button>
    </div>
  <% end %>
</form>

app/views/comments/edit.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/individual_comments/index.html.erb
<h2>Your Comments</h2>

<% @comments.each do |comment| %>

<ul class="list-group">
    <li class ="list-group-item">
      <%= comment.body %>
      <div>
        <small><%= time_ago_in_words(Time.now) %></small>
      </div>
    </li>
  </ul>

<% end %>

app/views/individual_links/index.html.erb
<h2>Your Posts</h2>

<% @links.each do |link| %>
  <ul class="list-group">
    <li class ="list-group-item">
      <%= link_to "#{link.title}", link_path(id: link.id) %>
      <%= link.description %>
      <small><%= time_ago_in_words(Time.now) %></small>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <body >

    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Front Page", links_path %></li>
            <li><%= link_to "New Post", new_link_path %></li>
            <li><%= link_to "Posts", individual_links_index_path %></li>
            <li><%= link_to "Comments", individual_comments_index_path %></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Login", login_new_path %>
            <li><%= link_to "Front Page", links_path %></li>  
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/edit.html.erb
<h2>Edit <%= @link.title %></h2>

<%= form_for @link do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
   <%= f.label :url %>
   <%= f.url_field :url %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Submit</button>
  </div>
<% end %>

app/views/links/index.html.erb
<h2>The Front Page of My Internet</h2>
<% @links.each do |link| %>
  <ul class="list-group">
      <li class ="list-group-item">
        <%= link_to "#{link.title}", link.url %>
        <%= link.description %>
      </li>
      <li class ="list-group-item">
        <%= link_to "Comment", link_path(id: link.id) %>
      </li>
  </ul>
<% end %>

<nav><%= paginate @links %></nav>

app/views/links/new.html.erb
<h2>Post your Link</h2>

<%= form_for @link do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
   <%= f.label :url %>
   <%= f.url_field :url %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Post</button>
  </div>
<% end %>

app/views/links/show.html.erb
<h2>Post</h2>

<% if current_user == @link.user %>
  <%= link_to "Edit", edit_link_path %>
  <%= link_to "Delete", link_path, method: :delete %>
<% end %>

<ul class="list-group">
    <li class ="list-group-item">
      <%= link_to "#{@link.title}", @link.url %>
      <%= @link.description %>
      <div class>
        by: <%= @link.user.user_name %>
        <small><%= time_ago_in_words(Time.now) %></small>
      </div>
    </li>
</ul>

<%= render 'comments/new' %>

<ul class="list-group">

    <% @link.comments.each do |comment| %>
    <li class ="list-group-item">
        <%= comment.body %>
        <div class>
          by: <%= comment.user.user_name %>
          <small><%= time_ago_in_words(Time.now) %></small>
        </div>
    </li>
    <% end %>
  </ul>

app/views/login/new.html.erb
<h2>Login</h2>

<%= form_tag login_path do %>
  <div class="form-group">
    <%= label_tag :user_name %>
    <%= text_field_tag :user_name %>
  </div>
  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Login</button>
  </div>
<% end %>

<p>
  Not a user?
  <%= link_to "Create Profile", new_user_path%>
</p>

app/views/users/edit.html.erb
<h2>Update Your Info</h2>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %>
 </div>
 <div class="form-group">
   <button type="submit" class="btn btn-success">Update</button>
 </div>
<% end %>

app/views/users/new.html.erb
<h2>Create a Profile</h2>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Sign Up</button>
  </div>    
<% end %>

app/views/users/show.html.erb
<h2>Your Information</h2>

<div>
  <%= link_to "Edit Info", edit_user_path %>
</div>

<ul class="list-group">
    <li class ="list-group-item">
      Username: <%= @user.user_name %>
    </li>
    <li class ="list-group-item">
      Email: <%= @user.email %>
    </li>

<div class="btn btn-danger">
  <%= link_to "Delete Account", user_path, method: :delete %>
</div>

app/views/users/update.html.erb
<h1>Update Your Info</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %>
 </div>
    <%= f.submit %>
<% end %>